-- InterviewHub Seed Questions Migration
-- Migration ID: 20260810000002_seed_questions.sql
-- Target Engine: PostgreSQL 15+ (Supabase)

-- ============================================================================
-- 1. SEED CATEGORIES (7 MVP Frontend Categories)
-- ============================================================================
INSERT INTO public.categories (id, name, slug, description, icon_name, sort_order) VALUES
  ('a0000000-0000-0000-0000-000000000001', 'HTML', 'html', 'Semantic HTML5, DOM structure, forms, and web accessibility (ARIA) fundamentals.', 'html5', 1),
  ('a0000000-0000-0000-0000-000000000002', 'CSS', 'css', 'Flexbox, CSS Grid, specificity, responsive design, animations, and Tailwind CSS.', 'css3', 2),
  ('a0000000-0000-0000-0000-000000000003', 'JavaScript', 'javascript', 'ES6+ syntax, closures, event loop, promises, async/await, and prototype chain.', 'javascript', 3),
  ('a0000000-0000-0000-0000-000000000004', 'React', 'react', 'Component lifecycle, state management, hooks, rendering optimization, and JSX.', 'react', 4),
  ('a0000000-0000-0000-0000-000000000005', 'TypeScript', 'typescript', 'Types vs. interfaces, generics, utility types, type narrowing, and strict compiler configs.', 'typescript', 5),
  ('a0000000-0000-0000-0000-000000000006', 'Web Fundamentals', 'web-fundamentals', 'HTTP/HTTPS, browser rendering pipeline, CORS, storage, and Web Vitals.', 'globe', 6),
  ('a0000000-0000-0000-0000-000000000007', 'Git', 'git', 'Branching workflows, rebase vs. merge, stash, cherry-pick, and conflict resolution.', 'git-branch', 7)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description;

-- ============================================================================
-- 2. SEED QUESTIONS (35 Verified Frontend Interview Questions)
-- ============================================================================

-- HTML Questions (5)
INSERT INTO public.questions (id, title, slug, category_id, topic, difficulty, type, short_summary, explanation, code_snippet, interview_tip, options, correct_answer, tags, sources, estimated_minutes, status) VALUES
(
  'q-html-01',
  'What is semantic HTML and why is it important for accessibility?',
  'semantic-html-accessibility',
  'a0000000-0000-0000-0000-000000000001',
  'Semantic HTML',
  'Beginner',
  'Multiple Choice',
  'Semantic HTML uses tags that convey the meaning of their content to browsers and screen readers rather than just visual presentation.',
  'Semantic HTML elements clearly describe their meaning in a human- and machine-readable way. Elements such as `<header>`, `<nav>`, `<main>`, `<article>`, `<section>`, and `<footer>` tell the browser, search engines, and assistive technologies (like screen readers) what type of content is contained within them.\n\n### Benefits of Semantic HTML:\n1. **Accessibility (a11y)**: Screen readers use landmark elements to navigate pages quickly.\n2. **SEO**: Search engines assign higher weighting to structured content.\n3. **Maintainability**: Clearer, self-documenting code structure for engineering teams.',
  '<!-- Good: Semantic Structure -->\n<header>\n  <nav>\n    <a href="/">Home</a>\n  </nav>\n</header>\n<main>\n  <article>\n    <h1>Understanding Semantic HTML</h1>\n  </article>\n</main>',
  'In an interview, emphasize that semantic HTML is the foundation of web accessibility (a11y). Mention landmarks like <main> and <nav> and explain that screen readers rely on them.',
  '["Using elements like <header>, <article>, and <nav> to structure documents based on content meaning.", "Using <div> and <span> tags with inline CSS styles for faster rendering.", "Writing HTML code without any CSS or JavaScript attributes.", "Using capitalized tags like <MAIN> and <SECTION> to improve SEO."]'::jsonb,
  'Using elements like <header>, <article>, and <nav> to structure documents based on content meaning.',
  ARRAY['html5', 'semantic', 'accessibility', 'a11y'],
  '[{"name": "MDN Web Docs — Semantics", "url": "https://developer.mozilla.org/en-US/docs/Glossary/Semantics"}]'::jsonb,
  3,
  'published'
),
(
  'q-html-02',
  'What is the purpose of the alt attribute on img tags?',
  'purpose-of-img-alt-attribute',
  'a0000000-0000-0000-0000-000000000001',
  'Accessibility',
  'Beginner',
  'Multiple Choice',
  'The alt attribute provides text alternatives for images when they fail to load or are read by screen readers for visually impaired users.',
  'The `alt` (alternative text) attribute is required on HTML `<img>` tags for accessibility. When an image cannot be rendered (e.g. broken link or slow network), the browser displays the `alt` text. More importantly, screen readers read this text aloud to visually impaired users.',
  '<!-- Accessible Image -->\n<img src="company-logo.png" alt="InterviewHub Official Logo" />\n\n<!-- Decorative Image (Skipped by Screen Readers) -->\n<img src="divider-line.svg" alt="" role="presentation" />',
  'Always mention that decorative images should have an empty alt attribute (alt="") so screen readers skip them instead of reading out filename paths.',
  '["It displays a hover tooltip text over the image.", "It provides text alternatives for screen readers and when images fail to load.", "It resizes the image automatically to fit the screen.", "It specifies the alignment of the image within text."]'::jsonb,
  'It provides text alternatives for screen readers and when images fail to load.',
  ARRAY['html', 'images', 'accessibility', 'attributes'],
  '[{"name": "MDN Web Docs — <img> alt attribute", "url": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt"}]'::jsonb,
  2,
  'published'
),
(
  'q-html-03',
  'True or False: The section tag should be used purely as a styling container like div.',
  'section-vs-div-usage',
  'a0000000-0000-0000-0000-000000000001',
  'Document Structure',
  'Junior',
  'True/False',
  'False. The section element represents a standalone thematic grouping of content, whereas div is a non-semantic layout wrapper.',
  '**False.** The `<section>` tag is a semantic element representing a generic standalone section of a document. It should typically include a heading (`<h2>`-`<h6>`). If you only need a container for styling or layout positioning, use `<div>`.',
  '<section aria-labelledby="features-heading">\n  <h2 id="features-heading font-bold">Platform Features</h2>\n  <p>Overview of features...</p>\n</section>',
  'Remember rule of thumb: If you need CSS styling or JS positioning without semantic meaning, use div. If content forms a distinct thematic group with a heading, use section.',
  '["True", "False"]'::jsonb,
  'False',
  ARRAY['html5', 'semantic', 'dom', 'structure'],
  '[{"name": "MDN Web Docs — <section>", "url": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section"}]'::jsonb,
  2,
  'published'
),
(
  'q-html-04',
  'How do data- attributes work in HTML5?',
  'html5-data-attributes-usage',
  'a0000000-0000-0000-0000-000000000001',
  'HTML5 APIs',
  'Junior',
  'Multiple Choice',
  'Custom data- attributes allow embedding custom dataset values directly on HTML elements, readable via dataset API in JavaScript.',
  'HTML5 `data-*` attributes let you store extra information on standard, semantic HTML elements without using non-standard attributes. In JS, you access them via `element.dataset`.',
  '<!-- HTML -->\n<button id="user-btn" data-user-id="1024" data-role="admin">\n  User Profile\n</button>\n\n<!-- JavaScript -->\n<script>\n  const btn = document.getElementById("user-btn");\n  console.log(btn.dataset.userId); // "1024"\n  console.log(btn.dataset.role);   // "admin"\n</script>',
  'Highlight that while data- attributes are convenient for UI state markers, sensitive security data should never be exposed in public HTML DOM attributes.',
  '["They allow storing custom data private to the page on any HTML element.", "They send background HTTP requests whenever the element is clicked.", "They encrypt element content before rendering.", "They define database table columns for client-side storage."]'::jsonb,
  'They allow storing custom data private to the page on any HTML element.',
  ARRAY['html5', 'dataset', 'attributes', 'dom'],
  '[{"name": "MDN Web Docs — Using data attributes", "url": "https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes"}]'::jsonb,
  3,
  'published'
),
(
  'q-html-05',
  'What is the difference between inline and block-level HTML elements?',
  'inline-vs-block-elements',
  'a0000000-0000-0000-0000-000000000001',
  'DOM Layout',
  'Beginner',
  'Multiple Choice',
  'Block elements start on a new line and stretch to full container width, whereas inline elements take up only as much width as necessary.',
  'By default, block-level elements (e.g. `<div>`, `<p>`, `<h1>`) begin on a new line and occupy the entire width of their parent container. Inline elements (e.g. `<span>`, `<a>`, `<strong>`) do not break onto a new line and only take up the width of their inner content.',
  '<!-- Block Example -->\n<div style="background: red;">Full Width Row</div>\n\n<!-- Inline Example -->\n<span>Word 1</span> <span>Word 2</span>',
  'Note that top/bottom margins and height properties do not apply to inline elements. To apply top/bottom padding/margin, set display: inline-block or block.',
  '["Block elements start on a new line and span full width; inline elements take only necessary content width.", "Inline elements can contain block elements, but block elements cannot contain inline elements.", "Block elements can only be styled with inline CSS.", "Inline elements automatically add top and bottom margins."]'::jsonb,
  'Block elements start on a new line and span full width; inline elements take only necessary content width.',
  ARRAY['html', 'block', 'inline', 'dom'],
  '[{"name": "MDN Web Docs — Block-level elements", "url": "https://developer.mozilla.org/en-US/docs/Glossary/Block-level_content"}]'::jsonb,
  3,
  'published'
),

-- CSS Questions (5)
(
  'q-css-01',
  'How does CSS Specificity get calculated when conflicting styles occur?',
  'css-specificity-calculation',
  'a0000000-0000-0000-0000-000000000002',
  'Specificity & Cascade',
  'Junior',
  'Multiple Choice',
  'CSS specificity is calculated using a 4-number tuple (inline, IDs, classes/attributes/pseudo-classes, elements/pseudo-elements).',
  'Specificity is the algorithm used by browsers to determine which CSS rule applies to an element when multiple rules conflict. \n\n### Specificity Weights:\n- **Inline styles**: (1, 0, 0, 0)\n- **IDs**: (0, 1, 0, 0)\n- **Classes, attributes, pseudo-classes**: (0, 0, 1, 0)\n- **Elements & pseudo-elements**: (0, 0, 0, 1)\n\n`!important` overrides normal specificity calculations.',
  '/* Specificity: (0, 1, 0, 0) - WINNER */\n#header { color: blue; }\n\n/* Specificity: (0, 0, 2, 0) */\n.nav .item { color: red; }',
  'Avoid overusing !important. Explain that writing low-specificity, modular classes (like BEM or Utility-first CSS) is cleaner than fighting specificity wars.',
  '["Tuple score: (Inline, ID, Class/Attribute/Pseudo-class, Element/Pseudo-element).", "The rule defined at the very top of the CSS file always wins.", "Random priority based on browser load speed.", "Class selectors always override ID selectors."]'::jsonb,
  'Tuple score: (Inline, ID, Class/Attribute/Pseudo-class, Element/Pseudo-element).',
  ARRAY['css', 'specificity', 'cascade', 'selectors'],
  '[{"name": "MDN Web Docs — Specificity", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity"}]'::jsonb,
  4,
  'published'
),
(
  'q-css-02',
  'What is the difference between Flexbox and CSS Grid layout systems?',
  'flexbox-vs-css-grid',
  'a0000000-0000-0000-0000-000000000002',
  'Layout Systems',
  'Junior',
  'Multiple Choice',
  'Flexbox is designed for 1-dimensional layouts (rows OR columns), whereas CSS Grid is designed for 2-dimensional layouts (rows AND columns).',
  'Flexbox is optimized for one-dimensional layouts along a single axis (either horizontal row or vertical column). CSS Grid is built for two-dimensional layouts, controlling rows and columns simultaneously.',
  '/* Flexbox: 1D Alignment */\n.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n\n/* CSS Grid: 2D Matrix */\n.gallery {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n  gap: 1rem;\n}',
  'State clearly: Flexbox is content-out (items dictate space), while Grid is layout-in (grid tracks dictate item placement). They complement each other.',
  '["Flexbox is 1-dimensional (content-first); CSS Grid is 2-dimensional (layout-first).", "Flexbox only works on mobile devices.", "CSS Grid cannot align items vertically.", "Flexbox cannot handle wrap lines."]'::jsonb,
  'Flexbox is 1-dimensional (content-first); CSS Grid is 2-dimensional (layout-first).',
  ARRAY['css', 'flexbox', 'grid', 'responsive'],
  '[{"name": "MDN Web Docs — Relationship of Grid Layout", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout"}]'::jsonb,
  4,
  'published'
),
(
  'q-css-03',
  'True or False: Setting box-sizing: border-box includes padding and border in the element width.',
  'box-sizing-border-box-behavior',
  'a0000000-0000-0000-0000-000000000002',
  'Box Model',
  'Beginner',
  'True/False',
  'True. border-box tells the browser to account for any border and padding in the values specified for width and height.',
  '**True.** Under `box-sizing: content-box` (browser default), padding and border are added outside the width. Under `border-box`, declared width includes content, padding, and border, preventing unexpected layout overflows.',
  '*, ::before, ::after {\n  box-sizing: border-box;\n}',
  'Mention that modern CSS resets universally apply `*, ::before, ::after { box-sizing: border-box; }` to simplify sizing calculations.',
  '["True", "False"]'::jsonb,
  'True',
  ARRAY['css', 'box-model', 'border-box', 'layout'],
  '[{"name": "MDN Web Docs — box-sizing", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing"}]'::jsonb,
  2,
  'published'
),
(
  'q-css-04',
  'What is the difference between display: none and visibility: hidden?',
  'display-none-vs-visibility-hidden',
  'a0000000-0000-0000-0000-000000000002',
  'Display & Visibility',
  'Beginner',
  'Multiple Choice',
  'display: none removes the element entirely from document flow, while visibility: hidden hides it but preserves its space in the layout.',
  '- `display: none`: The element is hidden and completely removed from document flow. Surrounding elements fill the empty space.\n- `visibility: hidden`: The element is invisible, but still occupies its exact width and height space in the page layout.',
  '.hidden-layout {\n  display: none; /* No space reserved */\n}\n\n.hidden-visual {\n  visibility: hidden; /* Space reserved */\n}',
  'Also note that screen readers ignore elements with display: none or visibility: hidden. To visually hide an element while keeping it accessible for screen readers, use sr-only utility classes.',
  '["display: none removes element from DOM flow; visibility: hidden hides it while preserving layout space.", "visibility: hidden deletes the HTML tag permanently.", "display: none only works on text nodes.", "There is no difference between them."]'::jsonb,
  'display: none removes element from DOM flow; visibility: hidden hides it while preserving layout space.',
  ARRAY['css', 'display', 'visibility', 'dom'],
  '[{"name": "MDN Web Docs — display", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/display"}]'::jsonb,
  3,
  'published'
),
(
  'q-css-05',
  'How does container queries differ from traditional media queries in modern CSS?',
  'container-queries-vs-media-queries',
  'a0000000-0000-0000-0000-000000000002',
  'Responsive Design',
  'Intermediate',
  'Multiple Choice',
  'Media queries respond to the viewport width, while Container queries respond to the size of a specific parent container.',
  'Container queries enable components to adapt based on the size of their parent container rather than the overall browser viewport. This makes components truly modular when placed in sidebars versus main content areas.',
  '@container (min-width: 400px) {\n  .card {\n    display: flex;\n    flex-direction: row;\n  }\n}',
  'Explain that container queries solve the "reusable component problem" where a component card needs to look different depending on whether it sits in a narrow sidebar or wide main grid.',
  '["Media queries check viewport width; Container queries check parent container width.", "Container queries require JavaScript to function.", "Media queries only work on desktop screens.", "Container queries replace flexbox completely."]'::jsonb,
  'Media queries check viewport width; Container queries check parent container width.',
  ARRAY['css', 'container-queries', 'responsive', 'modern-css'],
  '[{"name": "MDN Web Docs — CSS Container Queries", "url": "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries"}]'::jsonb,
  5,
  'published'
),

-- JavaScript Questions (5)
(
  'q-js-01',
  'What is a closure in JavaScript and what is a common practical use case?',
  'javascript-closures-explained',
  'a0000000-0000-0000-0000-000000000003',
  'Closures & Scope',
  'Junior',
  'Multiple Choice',
  'A closure is a function bundled with references to its surrounding state, allowing inner functions to access outer scope variables.',
  'A closure gives an inner function access to an outer function’s scope variables even after the outer function has finished executing.\n\n### Common Use Cases:\n1. Data privacy / encapsulation (emulating private variables).\n2. Function currying and partial application.\n3. Custom hooks in React (`useState` relies on closures under the hood).',
  'function createCounter() {\n  let count = 0; // Private variable via closure\n  return {\n    increment: () => ++count,\n    getCount: () => count,\n  };\n}\n\nconst counter = createCounter();\nconsole.log(counter.increment()); // 1\nconsole.log(counter.getCount());  // 1',
  'When asked about closures, give a simple counter example. Explain that the count variable is hidden from global scope and only modified through returned inner methods.',
  '["A function combined with its lexical environment, preserving outer variables after outer function execution.", "A method used to close database connections in Node.js.", "A syntax error when a function lacks a return statement.", "An event listener attached to the window object."]'::jsonb,
  'A function combined with its lexical environment, preserving outer variables after outer function execution.',
  ARRAY['javascript', 'closures', 'scope', 'es6'],
  '[{"name": "MDN Web Docs — Closures", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures"}]'::jsonb,
  4,
  'published'
),
(
  'q-js-02',
  'How does the JavaScript Event Loop process Call Stack and Microtask Queue?',
  'javascript-event-loop-microtasks',
  'a0000000-0000-0000-0000-000000000003',
  'Asynchronous JS',
  'Intermediate',
  'Multiple Choice',
  'The Event Loop executes all synchronous code on the call stack first, then drains the entire Microtask Queue before task queues.',
  'JavaScript is single-threaded. The Event Loop orchestrates async execution:\n1. **Call Stack**: Executes synchronous code.\n2. **Microtask Queue**: Promises (`.then`), `queueMicrotask`, `MutationObserver`. Entire queue is drained before next rendering.\n3. **Macrotask Queue**: `setTimeout`, `setInterval`, `requestAnimationFrame`.',
  'console.log("1"); // Sync\n\nsetTimeout(() => console.log("2"), 0); // Macrotask\n\nPromise.resolve().then(() => console.log("3")); // Microtask\n\nconsole.log("4"); // Sync\n\n// Output Order: 1 -> 4 -> 3 -> 2',
  'Walk through output order questions line-by-line: Synchronous logs print first, Promise.then callbacks run second, and setTimeout callbacks run last.',
  '["Drains call stack, drains microtasks (Promises/queueMicrotask), then processes single macrotask (setTimeout).", "Executes setTimeout before Promise handlers.", "Processes microtasks and macrotasks in random order.", "Runs async functions on separate multi-threaded CPU threads."]'::jsonb,
  'Drains call stack, drains microtasks (Promises/queueMicrotask), then processes single macrotask (setTimeout).',
  ARRAY['javascript', 'event-loop', 'async', 'promises'],
  '[{"name": "MDN Web Docs — Event loop", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop"}]'::jsonb,
  5,
  'published'
),
(
  'q-js-03',
  'True or False: Promises created with Promise.all() resolve even if one promise rejects.',
  'promise-all-rejection-behavior',
  'a0000000-0000-0000-0000-000000000003',
  'Promises',
  'Junior',
  'True/False',
  'False. Promise.all() fails fast and immediately rejects as soon as any single input promise rejects.',
  '**False.** `Promise.all()` rejects immediately if any promise in the array fails (short-circuiting). If you want all promises to settle regardless of outcome (rejections or fulfillments), use `Promise.allSettled()`.',
  '// Rejects immediately on first failure\nPromise.all([fetchUser(), fetchFailedApi()])\n  .catch(err => console.error("Fails fast:", err));',
  'Differentiate Promise.all() (all or nothing) from Promise.allSettled() (get status report of all promises regardless of failure).',
  '["True", "False"]'::jsonb,
  'False',
  ARRAY['javascript', 'promises', 'async', 'es6'],
  '[{"name": "MDN Web Docs — Promise.all()", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all"}]'::jsonb,
  3,
  'published'
),
(
  'q-js-04',
  'What is the key difference between == and === operators in JavaScript?',
  'loose-vs-strict-equality-operators',
  'a0000000-0000-0000-0000-000000000003',
  'Coercion & Equality',
  'Beginner',
  'Multiple Choice',
  '== performs implicit type coercion before comparing values, whereas === checks both value equality and strict type equality.',
  '`==` (loose equality) converts operands to a common type before evaluation, leading to confusing results like `''0'' == 0` (true) or `[] == false` (true). `===` (strict equality) checks value and type without coercion.',
  'console.log(5 == "5");  // true (type coercion)\nconsole.log(5 === "5"); // false (strict type check)',
  'Always recommend using === in production code to avoid subtle bugs caused by implicit JavaScript type coercion.',
  '["== performs type coercion before comparison; === compares both value and type without coercion.", "=== is for numbers and == is for strings.", "== is faster than ===.", "=== converts objects to booleans automatically."]'::jsonb,
  '== performs type coercion before comparison; === compares both value and type without coercion.',
  ARRAY['javascript', 'operators', 'equality', 'types'],
  '[{"name": "MDN Web Docs — Equality comparisons", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness"}]'::jsonb,
  2,
  'published'
),
(
  'q-js-05',
  'How does keyword "this" get determined in regular functions versus arrow functions?',
  'this-keyword-regular-vs-arrow-functions',
  'a0000000-0000-0000-0000-000000000003',
  'Functions & Execution Context',
  'Junior',
  'Multiple Choice',
  'Regular functions bind "this" dynamically based on invocation, while arrow functions capture "this" lexically from surrounding scope.',
  'In regular functions, `this` depends on how the function is invoked (e.g. method call, standalone call, call/apply/bind). Arrow functions do NOT have their own `this` binding; they inherit `this` lexically from their enclosing parent scope.',
  'const obj = {\n  name: "InterviewHub",\n  regular: function() { console.log(this.name); },\n  arrow: () => { console.log(this.name); },\n};\n\nobj.regular(); // "InterviewHub"\nobj.arrow();   // undefined (global scope)',
  'Remember: Arrow functions cannot be used as constructors (with `new`) and do not have an `arguments` object.',
  '["Regular functions bind \"this\" dynamically at call-time; arrow functions capture \"this\" lexically from enclosing scope.", "Arrow functions create a new \"this\" context every time they are called.", "Regular functions cannot be called as object methods.", "There is no difference in \"this\" behavior."]'::jsonb,
  'Regular functions bind "this" dynamically at call-time; arrow functions capture "this" lexically from enclosing scope.',
  ARRAY['javascript', 'this', 'arrow-functions', 'functions'],
  '[{"name": "MDN Web Docs — Arrow function expressions", "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions"}]'::jsonb,
  4,
  'published'
),

-- React Questions (6)
(
  'q-react-01',
  'What is the Virtual DOM in React and how does reconciliation work?',
  'virtual-dom-reconciliation-react',
  'a0000000-0000-0000-0000-000000000004',
  'Virtual DOM',
  'Beginner',
  'Multiple Choice',
  'The Virtual DOM is a lightweight in-memory representation of real DOM. React diffs it against previous state to apply minimal updates.',
  'Direct DOM manipulation is slow. React creates a lightweight Virtual DOM (tree of JavaScript objects). When state changes:\n1. React renders a new Virtual DOM tree.\n2. **Diffing Algorithm**: Compares new VDOM with previous VDOM.\n3. **Reconciliation**: Batches and applies only the changed elements to the real browser DOM.',
  '// React Element (Virtual DOM Node representation)\nconst element = {\n  type: "h1",\n  props: { className: "title", children: "Hello React" }\n};',
  'Highlight that Virtual DOM provides developer productivity and consistent declarative rendering across platforms (React Native, Web).',
  '["An in-memory object tree diffed against previous state to batch minimal real DOM updates.", "A direct copy of browser HTML saved on local disk.", "A browser plugin required to run React applications.", "A CSS preprocessor built into React compiler."]'::jsonb,
  'An in-memory object tree diffed against previous state to batch minimal real DOM updates.',
  ARRAY['react', 'virtual-dom', 'reconciliation', 'core'],
  '[{"name": "React Docs — Preserving and Resetting State", "url": "https://react.dev/learn/preserving-and-resetting-state"}]'::jsonb,
  3,
  'published'
),
(
  'q-react-02',
  'When and why should you pass a cleanup function inside useEffect?',
  'useeffect-cleanup-function-use-cases',
  'a0000000-0000-0000-0000-000000000004',
  'React Hooks',
  'Junior',
  'Multiple Choice',
  'Cleanup functions run before component unmount or re-render to cancel subscriptions, clear timers, and prevent memory leaks.',
  'The cleanup function returned by `useEffect` runs before the component unmounts or before the effect re-runs on dependency changes.\n\n### Common Use Cases:\n- `removeEventListener` for window scroll/resize events\n- `clearInterval` / `clearTimeout`\n- `controller.abort()` for AbortController fetch requests.',
  'useEffect(() => {\n  const handleResize = () => setWidth(window.innerWidth);\n  window.addEventListener("resize", handleResize);\n\n  // Cleanup function\n  return () => {\n    window.removeEventListener("resize", handleResize);\n  };\n}, []);',
  'Emphasize memory leak prevention. Give an example of removing event listeners so unmounted components do not keep background listeners active.',
  '["To unsubscribe from events, clear timers, or abort fetch requests before unmounting/re-rendering.", "To reset component state back to initial default props.", "To force synchronous DOM reflows.", "To clear local browser cache automatically."]'::jsonb,
  'To unsubscribe from events, clear timers, or abort fetch requests before unmounting/re-rendering.',
  ARRAY['react', 'useeffect', 'hooks', 'lifecycle'],
  '[{"name": "React Docs — Synchronizing with Effects", "url": "https://react.dev/learn/synchronizing-with-effects"}]'::jsonb,
  4,
  'published'
),
(
  'q-react-03',
  'True or False: React state updates made via useState setter functions are asynchronous and batched.',
  'react-state-batching-behavior',
  'a0000000-0000-0000-0000-000000000004',
  'State Management',
  'Junior',
  'True/False',
  'True. React batches multiple state updates inside event handlers into a single re-render for performance optimization.',
  '**True.** React batches state updates to prevent multiple expensive re-renders within a single event loop tick. To compute new state based on previous state reliably, use the functional update form: `setCount(prev => prev + 1)`.',
  '// Functional updater ensures correct calculation\nsetCount(prev => prev + 1);\nsetCount(prev => prev + 1);',
  'Show functional state updater syntax `setCount(prev => prev + 1)` when multiple state calls happen consecutively.',
  '["True", "False"]'::jsonb,
  'True',
  ARRAY['react', 'usestate', 'batching', 'rendering'],
  '[{"name": "React Docs — Queueing State Updates", "url": "https://react.dev/learn/queueing-a-series-of-state-updates"}]'::jsonb,
  3,
  'published'
),
(
  'q-react-04',
  'What is the primary difference between useMemo and useCallback hooks?',
  'usememo-vs-usecallback-difference',
  'a0000000-0000-0000-0000-000000000004',
  'Performance Optimization',
  'Intermediate',
  'Multiple Choice',
  'useMemo memoizes the result of a computed calculation, whereas useCallback memoizes a function instance reference between renders.',
  '- `useMemo(() => computeExpensiveValue(a, b), [a, b])`: Memoizes calculated data value.\n- `useCallback(() => fn(a), [a])`: Memoizes function definition to prevent child component re-renders when passed as callback prop (`React.memo`).',
  '// Caches calculation value\nconst memoizedValue = useMemo(() => calculateTotal(items), [items]);\n\n// Caches function reference\nconst handleClick = useCallback(() => console.log("Clicked"), []);',
  'Mention premature optimization warning: Don’t wrap every function in useCallback/useMemo unless passing to memoized children or computing heavy arrays.',
  '["useMemo caches calculated return values; useCallback caches function instance references.", "useMemo is for API fetching; useCallback is for styling.", "useCallback runs before render; useMemo runs after render.", "They are aliases for the exact same underlying hook."]'::jsonb,
  'useMemo caches calculated return values; useCallback caches function instance references.',
  ARRAY['react', 'usememo', 'usecallback', 'performance'],
  '[{"name": "React Docs — useMemo", "url": "https://react.dev/reference/react/useMemo"}]'::jsonb,
  4,
  'published'
),
(
  'q-react-05',
  'Why are keys important when rendering lists in React components?',
  'importance-of-keys-in-react-lists',
  'a0000000-0000-0000-0000-000000000004',
  'Lists & Keys',
  'Beginner',
  'Multiple Choice',
  'Keys give array elements stable identities so React can efficiently track insertions, deletions, and re-orders during reconciliation.',
  'Keys help React identify which items have changed, been added, or been removed. Unique keys (like database IDs) allow React to reuse existing DOM nodes rather than recreating entire lists on re-order.',
  '// Good: Unique database ID as key\n{items.map(item => (\n  <li key={item.id}>{item.name}</li>\n))}',
  'Warn against using array index as key when list order can change, as it can cause state bugs in child inputs.',
  '["They provide stable identities for list items during virtual DOM diffing.", "They encrypt list items before sending to server.", "They are required for CSS flexbox styling.", "They automatically sort array items alphabetically."]'::jsonb,
  'They provide stable identities for list items during virtual DOM diffing.',
  ARRAY['react', 'keys', 'lists', 'rendering'],
  '[{"name": "React Docs — Rendering Lists", "url": "https://react.dev/learn/rendering-lists"}]'::jsonb,
  3,
  'published'
),
(
  'q-react-06',
  'What is the purpose of React.memo higher-order component?',
  'react-memo-higher-order-component',
  'a0000000-0000-0000-0000-000000000004',
  'Performance Optimization',
  'Junior',
  'Multiple Choice',
  'React.memo skips re-rendering a component if its incoming props have not shallowly changed between renders.',
  '`React.memo` is a Higher-Order Component that wraps a functional component. It performs a shallow comparison of current props versus next props and skips re-rendering if props are equal.',
  'const MyComponent = React.memo(function MyComponent(props) {\n  return <div>{props.title}</div>;\n});',
  'Explain shallow comparison: Object/function props will recreate reference on parent render unless wrapped in useMemo/useCallback.',
  '["It memoizes a component render output, skipping re-renders when props remain unchanged.", "It creates global state accessible by all components.", "It converts class components into functional components.", "It automatically handles API error boundaries."]'::jsonb,
  'It memoizes a component render output, skipping re-renders when props remain unchanged.',
  ARRAY['react', 'react-memo', 'hoc', 'performance'],
  '[{"name": "React Docs — memo", "url": "https://react.dev/reference/react/memo"}]'::jsonb,
  3,
  'published'
),

-- TypeScript Questions (5)
(
  'q-ts-01',
  'What is the key difference between Interface and Type alias in TypeScript?',
  'typescript-interface-vs-type-alias',
  'a0000000-0000-0000-0000-000000000005',
  'Type Systems',
  'Junior',
  'Multiple Choice',
  'Interfaces are extendable via declaration merging and inheritance, while Type aliases can represent unions, primitives, and tuples.',
  '- **Interface**: Best for object shapes and OOP inheritance (`extends`). Supports declaration merging (multiple `interface User` declarations merge).\n- **Type**: Best for unions (`type Status = "pending" | "approved"`), primitives, tuples, and mapped types.',
  '// Type Union\ntype Status = "loading" | "success" | "error";\n\n// Interface Object Shape\ninterface User {\n  id: string;\n  name: string;\n}',
  'State your team rule of thumb: Use interface for component props and object shapes; use type for unions and utility aliases.',
  '["Interfaces support declaration merging and OOP extends; Types support unions, primitives, and intersections.", "Type aliases are compiled to JavaScript objects; Interfaces are deleted.", "Interfaces cannot define object shapes.", "Types only work with numbers and booleans."]'::jsonb,
  'Interfaces support declaration merging and OOP extends; Types support unions, primitives, and intersections.',
  ARRAY['typescript', 'interface', 'type-alias', 'types'],
  '[{"name": "TypeScript Handbook — Type Aliases vs Interfaces", "url": "https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces"}]'::jsonb,
  4,
  'published'
),
(
  'q-ts-02',
  'How does type narrowing work with discriminant unions in TypeScript?',
  'typescript-discriminant-unions-narrowing',
  'a0000000-0000-0000-0000-000000000005',
  'Type Narrowing',
  'Intermediate',
  'Multiple Choice',
  'Discriminant unions use a shared literal property (like type or status) to allow the compiler to narrow complex object branches.',
  'A discriminated union is a pattern where every object in a union contains a common property with literal types (the "discriminant"). Checking this property inside a `switch` or `if` narrows the object type automatically.',
  'type Response =\n  | { status: "success"; data: string }\n  | { status: "error"; message: string };\n\nfunction handle(res: Response) {\n  if (res.status === "success") {\n    console.log(res.data); // Narrowed safely!\n  } else {\n    console.error(res.message);\n  }\n}',
  'Mention that discriminant unions make state machines (like Redux or async state handling) completely type-safe.',
  '["Using a common literal discriminator property (e.g. status) to narrow object types in switch statements.", "Using try/catch blocks around every TypeScript function.", "Converting all types to any before calling properties.", "Disabling strict null checks in tsconfig.json."]'::jsonb,
  'Using a common literal discriminator property (e.g. status) to narrow object types in switch statements.',
  ARRAY['typescript', 'narrowing', 'unions', 'type-safety'],
  '[{"name": "TypeScript Handbook — Discriminated Unions", "url": "https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions"}]'::jsonb,
  5,
  'published'
),
(
  'q-ts-03',
  'True or False: The unknown type is safer than the any type because operations on unknown require type checking.',
  'typescript-unknown-vs-any-safety',
  'a0000000-0000-0000-0000-000000000005',
  'Type Safety',
  'Beginner',
  'True/False',
  'True. unknown forces developers to perform type checks or assertions before invoking methods or performing arithmetic.',
  '**True.** `any` disables all type checking. `unknown` represents any value, but TypeScript blocks method invocation or property access until type guard narrowing (e.g. `typeof x === "string"`) is performed.',
  'let val: unknown = "Hello";\n// val.toUpperCase(); // Error: Type is unknown\n\nif (typeof val === "string") {\n  console.log(val.toUpperCase()); // Safe!\n}',
  'Recommend using unknown over any for external dynamic data (like JSON.parse or unknown API responses).',
  '["True", "False"]'::jsonb,
  'True',
  ARRAY['typescript', 'unknown', 'any', 'strict-mode'],
  '[{"name": "TypeScript Handbook — Unknown", "url": "https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown"}]'::jsonb,
  2,
  'published'
),
(
  'q-ts-04',
  'What is the purpose of TypeScript Generics in reusable components?',
  'typescript-generics-reusable-components',
  'a0000000-0000-0000-0000-000000000005',
  'Generics',
  'Junior',
  'Multiple Choice',
  'Generics allow functions and classes to capture type variables, enforcing type safety without locking logic to a single data type.',
  'Generics allow creating components or utility functions that work over a variety of types rather than a single one, while retaining type safety.',
  'interface ApiResponse<T> {\n  data: T;\n  status: number;\n}\n\nconst userRes: ApiResponse<{ name: string }> = {\n  data: { name: "Alex" },\n  status: 200,\n};',
  'Give example of generic ApiResponse<T> where T represents payload data model.',
  '["They allow passing type variables to functions/interfaces to enforce type safety across varying data types.", "They automatically generate database schemas at compile time.", "They allow writing TypeScript without type annotations.", "They convert asynchronous code to synchronous code."]'::jsonb,
  'They allow passing type variables to functions/interfaces to enforce type safety across varying data types.',
  ARRAY['typescript', 'generics', 'reusability', 'type-safety'],
  '[{"name": "TypeScript Handbook — Generics", "url": "https://www.typescriptlang.org/docs/handbook/2/generics.html"}]'::jsonb,
  4,
  'published'
),
(
  'q-ts-05',
  'What do built-in utility types Partial<T> and Readonly<T> accomplish?',
  'typescript-utility-types-partial-readonly',
  'a0000000-0000-0000-0000-000000000005',
  'Utility Types',
  'Junior',
  'Multiple Choice',
  'Partial<T> makes all properties optional, whereas Readonly<T> marks all properties immutably read-only after assignment.',
  '- `Partial<T>`: Constructs a type with all properties of T set to optional (`?`). Great for update form payloads.\n- `Readonly<T>`: Constructs a type with all properties of T set to `readonly`. Modifying properties triggers compiler errors.',
  'interface User { id: string; name: string; }\n\ntype UpdateUserDto = Partial<User>; // { id?: string; name?: string; }\ntype ImmutableUser = Readonly<User>;',
  'Mention other common utility types like Pick<T, K>, Omit<T, K>, and Record<K, T>.',
  '["Partial<T> sets all properties to optional; Readonly<T> prevents property mutations.", "Partial<T> deletes properties; Readonly<T> converts properties to strings.", "Readonly<T> makes objects private to local scope.", "They perform runtime Object.freeze calls."]'::jsonb,
  'Partial<T> sets all properties to optional; Readonly<T> prevents property mutations.',
  ARRAY['typescript', 'utility-types', 'partial', 'readonly'],
  '[{"name": "TypeScript Handbook — Utility Types", "url": "https://www.typescriptlang.org/docs/handbook/utility-types.html"}]'::jsonb,
  3,
  'published'
),

-- Web Fundamentals Questions (5)
(
  'q-wf-01',
  'What happens step-by-step when you type a URL into the browser address bar?',
  'browser-url-request-lifecycle',
  'a0000000-0000-0000-0000-000000000006',
  'Browser Architecture',
  'Junior',
  'Multiple Choice',
  'DNS lookup resolves IP, TCP handshake establishes connection, TLS handshake secures it, HTTP request sent, HTML parsed into DOM.',
  '1. **DNS Lookup**: Resolves domain name into IP address.\n2. **TCP Handshake**: SYN, SYN-ACK, ACK to connect.\n3. **TLS Handshake**: Negotiates encryption keys for HTTPS.\n4. **HTTP Request/Response**: Server returns HTML payload.\n5. **Rendering Engine**: Parses HTML into DOM, CSS into CSSOM, calculates layout, paints pixels.',
  'DNS -> TCP -> TLS -> HTTP GET -> DOM Parsing -> Layout -> Paint',
  'Walk through stages sequentially: Network resolution -> Transport security -> HTTP payload -> Browser Critical Rendering Path.',
  '["DNS resolution -> TCP 3-way handshake -> TLS handshake -> HTTP GET request -> Server Response -> DOM/CSSOM parsing & rendering.", "Browser downloads JavaScript engine first, then contacts server.", "Server compiles HTML to C++ binary before sending to client.", "DNS sends HTML file directly to user CPU."]'::jsonb,
  'DNS resolution -> TCP 3-way handshake -> TLS handshake -> HTTP GET request -> Server Response -> DOM/CSSOM parsing & rendering.',
  ARRAY['web-fundamentals', 'browser', 'dns', 'http'],
  '[{"name": "MDN Web Docs — How browsers work", "url": "https://developer.mozilla.org/en-US/docs/Web/Performance/How_browsers_work"}]'::jsonb,
  5,
  'published'
),
(
  'q-wf-02',
  'What is CORS (Cross-Origin Resource Sharing) and why does the browser enforce it?',
  'cors-cross-origin-resource-sharing',
  'a0000000-0000-0000-0000-000000000006',
  'Web Security',
  'Junior',
  'Multiple Choice',
  'CORS is a browser security mechanism that uses HTTP headers to restrict cross-origin HTTP requests initiated from scripts.',
  'Browsers enforce the **Same-Origin Policy** (SOP) by default (matching protocol, domain, port). CORS allows servers to specify which external origins are allowed to read responses via `Access-Control-Allow-Origin` headers.',
  '/* Server Response Header */\nAccess-Control-Allow-Origin: https://interviewhub.dev\nAccess-Control-Allow-Methods: GET, POST, OPTIONS',
  'Clarify: CORS is enforced by the BROWSER, not the server. The server still processes the request, but browser blocks JS from reading the response if CORS headers fail.',
  '["A browser security mechanism using HTTP headers to allow or block cross-origin requests.", "A server firewall that blocks requests from mobile phones.", "A database query optimization protocol.", "An authentication token standard replacing JWT."]'::jsonb,
  'A browser security mechanism using HTTP headers to allow or block cross-origin requests.',
  ARRAY['web-fundamentals', 'cors', 'security', 'http'],
  '[{"name": "MDN Web Docs — CORS", "url": "https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"}]'::jsonb,
  4,
  'published'
),
(
  'q-wf-03',
  'True or False: HTTP/2 allows multiplexing multiple requests over a single TCP connection.',
  'http2-multiplexing-feature',
  'a0000000-0000-0000-0000-000000000006',
  'HTTP Protocols',
  'Intermediate',
  'True/False',
  'True. HTTP/2 multiplexing eliminates head-of-line blocking by sending concurrent request frames interleaved over one TCP pipe.',
  '**True.** HTTP/1.1 required separate TCP connections or serial head-of-line blocking. HTTP/2 splits messages into binary frames and interleaves them concurrently over a single TCP connection.',
  'HTTP/1.1: Request 1 -> Wait -> Request 2 -> Wait\nHTTP/2:   Stream 1 & Stream 2 & Stream 3 (Concurrent Multiplexing)',
  'Mention that HTTP/2 also supports Server Push and Header Compression (HPACK).',
  '["True", "False"]'::jsonb,
  'True',
  ARRAY['web-fundamentals', 'http2', 'networking', 'performance'],
  '[{"name": "MDN Web Docs — HTTP/2", "url": "https://developer.mozilla.org/en-US/docs/Glossary/HTTP_2"}]'::jsonb,
  3,
  'published'
),
(
  'q-wf-04',
  'What is the key difference between localStorage, sessionStorage, and Cookies?',
  'localstorage-sessionstorage-cookies-comparison',
  'a0000000-0000-0000-0000-000000000006',
  'Browser Storage',
  'Beginner',
  'Multiple Choice',
  'localStorage persists until cleared, sessionStorage clears on tab close, and Cookies send storage data with every HTTP request.',
  '- **localStorage**: 5MB+, persists permanently until explicitly deleted.\n- **sessionStorage**: 5MB+, scope tied to current browser tab.\n- **Cookies**: ~4KB, sent automatically in HTTP headers (`Cookie`), supports `HttpOnly` security flag.',
  '// Local Storage\nlocalStorage.setItem("theme", "dark");\n\n// Session Storage\nsessionStorage.setItem("tempKey", "12345");',
  'Highlight HttpOnly cookies for sensitive auth tokens to prevent XSS script theft.',
  '["localStorage persists across sessions; sessionStorage clears on tab close; Cookies attach to HTTP requests.", "Cookies hold 5MB data; localStorage holds 4KB data.", "sessionStorage saves data permanently on server hard drive.", "localStorage data is automatically sent in HTTP header."]'::jsonb,
  'localStorage persists across sessions; sessionStorage clears on tab close; Cookies attach to HTTP requests.',
  ARRAY['web-fundamentals', 'storage', 'cookies', 'browser'],
  '[{"name": "MDN Web Docs — localStorage", "url": "https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage"}]'::jsonb,
  3,
  'published'
),
(
  'q-wf-05',
  'What are Core Web Vitals (LCP, FID/INP, CLS) and why do they matter?',
  'core-web-vitals-performance-metrics',
  'a0000000-0000-0000-0000-000000000006',
  'Web Performance',
  'Junior',
  'Multiple Choice',
  'Core Web Vitals measure user experience metrics: LCP (loading speed), INP (interactivity responsiveness), and CLS (visual stability).',
  '1. **LCP (Largest Contentful Paint)**: Measures loading performance (< 2.5s).\n2. **INP (Interaction to Next Paint)**: Measures page responsiveness to clicks (< 200ms).\n3. **CLS (Cumulative Layout Shift)**: Measures visual layout shifts during page render (< 0.1).',
  '<!-- Set width/height on images to prevent CLS layout shifts -->\n<img src="banner.webp" width="800" height="400" alt="Banner" />',
  'Mention that images without set width/height cause bad CLS scores because layout shifts when image downloads finish.',
  '["Google metrics measuring loading (LCP), responsiveness (INP/FID), and layout stability (CLS).", "Security protocols for checking SSL certificates.", "Database indexing rules for faster SQL joins.", "HTML validator tests run by W3C."]'::jsonb,
  'Google metrics measuring loading (LCP), responsiveness (INP/FID), and layout stability (CLS).',
  ARRAY['web-fundamentals', 'performance', 'web-vitals', 'seo'],
  '[{"name": "web.dev — Core Web Vitals", "url": "https://web.dev/vitals/"}]'::jsonb,
  4,
  'published'
),

-- Git Questions (5)
(
  'q-git-01',
  'What is the primary difference between git merge and git rebase?',
  'git-merge-vs-git-rebase',
  'a0000000-0000-0000-0000-000000000007',
  'Branching Workflows',
  'Junior',
  'Multiple Choice',
  'git merge creates a new merge commit combining history, while git rebase rewrites linear commit history on top of base branch.',
  '- `git merge feature`: Creates a non-destructive merge commit, preserving exact historical commit timestamps.\n- `git rebase main`: Moves feature branch commits onto top of latest main branch, creating a clean linear project history.',
  '# Merge approach\ngit checkout main\ngit merge feature-auth\n\n# Rebase approach\ngit checkout feature-auth\ngit rebase main',
  'Golden Rule of Rebase: Never rebase commits that have already been pushed to a public/shared branch.',
  '["git merge preserves true chronological history via merge commit; git rebase rewrites linear history onto target branch.", "git rebase deletes your branch commits permanently.", "git merge can only be run by repository owners.", "There is no difference in commit history."]'::jsonb,
  'git merge preserves true chronological history via merge commit; git rebase rewrites linear history onto target branch.',
  ARRAY['git', 'merge', 'rebase', 'version-control'],
  '[{"name": "Git Docs — Merging vs Rebasing", "url": "https://git-scm.com/book/en/v2/Git-Branching-Rebasing"}]'::jsonb,
  4,
  'published'
),
(
  'q-git-02',
  'How does git stash help during context switching in working directories?',
  'git-stash-command-usage',
  'a0000000-0000-0000-0000-000000000007',
  'Worktree Management',
  'Beginner',
  'Multiple Choice',
  'git stash temporarily shelves uncommitted modifications so you can switch branches cleanly without committing incomplete work.',
  '`git stash` takes your uncommitted dirty working directory changes, saves them on a stack, and reverts your working directory back to HEAD commit.',
  'git stash             # Save uncommitted changes\ngit checkout hotfix   # Switch branch cleanly\n# ... fix bug ...\ngit checkout feature\ngit stash pop         # Re-apply stashed changes',
  'Know the main commands: git stash, git stash pop (apply and remove from stack), git stash list.',
  '["Temporarily saves modified tracked files on a stack without committing.", "Deletes uncommitted files permanently.", "Pushes uncommitted code directly to remote origin.", "Creates a new git repository."]'::jsonb,
  'Temporarily saves modified tracked files on a stack without committing.',
  ARRAY['git', 'stash', 'workflow', 'command-line'],
  '[{"name": "Git Docs — git-stash", "url": "https://git-scm.com/docs/git-stash"}]'::jsonb,
  3,
  'published'
),
(
  'q-git-03',
  'True or False: git reset --hard preserves local changes in your working directory.',
  'git-reset-hard-destructive-nature',
  'a0000000-0000-0000-0000-000000000007',
  'Undo & Reset',
  'Junior',
  'True/False',
  'False. git reset --hard destructively discards all uncommitted modifications and resets staging and working tree to target commit.',
  '**False.** `git reset --hard` is a destructive operation. It resets the index and working directory, discarding all uncommitted changes since target commit.',
  'git reset --hard HEAD~1 # Destructively removes last commit & changes',
  'Differentiate reset modes: --soft (keeps changes staged), --mixed (keeps changes in working directory unstaged), --hard (discards changes entirely).',
  '["True", "False"]'::jsonb,
  'False',
  ARRAY['git', 'reset', 'destructive', 'history'],
  '[{"name": "Git Docs — git-reset", "url": "https://git-scm.com/docs/git-reset"}]'::jsonb,
  2,
  'published'
),
(
  'q-git-04',
  'What does git cherry-pick accomplish in multi-branch repositories?',
  'git-cherry-pick-single-commit',
  'a0000000-0000-0000-0000-000000000007',
  'Advanced Git',
  'Intermediate',
  'Multiple Choice',
  'git cherry-pick applies the exact changes introduced by a specific existing commit from another branch onto your current branch.',
  '`git cherry-pick <commit-hash>` picks a single commit from any branch and applies its patch onto your current active branch.',
  'git checkout release-v1.2\ngit cherry-pick a1b2c3d4 # Apply single hotfix commit',
  'Use case: Porting a urgent hotfix commit from main branch back into an ongoing release branch.',
  '["Applies the change introduced by a specific existing commit from another branch to the current branch.", "Deletes specified commit from remote repository.", "Selects best commit based on code style.", "Creates a pull request automatically."]'::jsonb,
  'Applies the change introduced by a specific existing commit from another branch to the current branch.',
  ARRAY['git', 'cherry-pick', 'commits', 'branches'],
  '[{"name": "Git Docs — git-cherry-pick", "url": "https://git-scm.com/docs/git-cherry-pick"}]'::jsonb,
  4,
  'published'
),
(
  'q-git-05',
  'How do merge conflicts occur and how are they resolved in Git?',
  'git-merge-conflict-resolution',
  'a0000000-0000-0000-0000-000000000007',
  'Conflict Resolution',
  'Beginner',
  'Multiple Choice',
  'Merge conflicts occur when competing edits are made to the same line. Developers resolve conflict markers manually and commit.',
  'Git inserts conflict markers:\n`<<<<<<< HEAD` (current branch)\n`=======` (separator)\n`>>>>>>> branch` (incoming branch)\nDevelopers resolve conflicts manually, remove markers, stage via `git add`, and run `git commit`.',
  '<<<<<<< HEAD\nconst apiUrl = "https://api.v1.dev";\n=======\nconst apiUrl = "https://api.v2.dev";\n>>>>>>> feature-api-v2',
  'Emphasize communication: If unsure about conflicting code, talk to the teammate who wrote the competing lines before resolving.',
  '["When competing edits occur on same lines. Resolved by editing conflict markers (<<<<<<< / >>>>>>>) and staging.", "When two developers use different OS versions.", "When git repository runs out of disk storage space.", "When commit messages contain special characters."]'::jsonb,
  'When competing edits occur on same lines. Resolved by editing conflict markers (<<<<<<< / >>>>>>>) and staging.',
  ARRAY['git', 'merge-conflict', 'resolution', 'workflow'],
  '[{"name": "Git Docs — Basic Merge Conflicts", "url": "https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#_basic_merge_conflicts"}]'::jsonb,
  3,
  'published'
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  explanation = EXCLUDED.explanation,
  code_snippet = EXCLUDED.code_snippet,
  interview_tip = EXCLUDED.interview_tip,
  options = EXCLUDED.options,
  correct_answer = EXCLUDED.correct_answer,
  tags = EXCLUDED.tags,
  sources = EXCLUDED.sources,
  updated_at = NOW();
